server:
  port: 8080
  servlet:
    context-path: /mybatis
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.104:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化线程数
      initial-size: 10
      #最小值
      min-idle: 10
      #最大值
      max-active: 20
      #最大等待时间
      max-wait: 6000
      #sql验证
      validation-query: select 1 from dual
      #检查空闲连接的频率
      time-between-eviction-runs-millis: 60000
      #池中某个连接的空闲时长达到 N 毫秒后连接池在下次检查空闲连接时，将回收该连接
      min-evictable-idle-time-millis: 30000
      #当程序请求连接，池在分配连接时，是否先检查该连接是否有效。
      test-while-idle: true
      #程序申请连接时,进行连接有效性检查（低效，影响性能）
      test-on-borrow: false
      #程序返还连接时,进行连接有效性检查（低效，影响性能）
      test-on-return: false
      #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-open-prepared-statements: -1

  profiles:
    active: test
  application:
    name: springboot-mybatis

mybatis:
  #扫描xml所在的位置
  mapper-locations: classpath*:com/akon/springboot/mybatis/mapper/*.xml
logging:
  level:
    root: info
    com.akon.springboot.mybatis.model: debug
  file:
    path: ../logs


